## 📊 2-7 Pandas 데이터 입출력 (CSV / Excel)

In [17]:
# 경로 확인
import os
print(os.getcwd())

c:\Users\06pc-00\Documents\SJ\data

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.DataFrame({
    "이름" : ["철수","영희"],
    "점수" : [90,80]
})
df

   이름  점수
0  철수  90
1  영희  80

In [20]:
df.to_csv("source.csv",encoding="cp949")

# 인덱스 없이 저장

In [21]:
df.to_csv("score.csv", index=False, encoding='cp949')

# 해더가 없는 데이터프레임 저장

In [22]:
df.to_csv("score2.csv",index=False, header=False, encoding='cp949')

# 해더 이름을 직접 지정하여 저장

In [23]:
df.to_csv (
    "score3.csv",
    index=False,
    header=['학생이름','시험점수'],
    encoding='cp949')

In [11]:
%pip install openpyxl

Collecting openpyxl
  Obtaining dependency information for openpyxl from https://files.pythonhosted.org/packages/c0/da/977ded879c29cbd04de313843e76868e6e13408a94ed6b987245dc7c8506/openpyxl-3.1.5-py2.py3-none-any.whl.metadata
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Obtaining dependency information for et-xmlfile from https://files.pythonhosted.org/packages/c1/8b/5fe2cc11fee489817272089c4203e679c63b570a5aaeb18d852ae3cbba6a/et_xmlfile-2.0.0-py3-none-any.whl.metadata
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
   ---------------------------------------- 0.0/250.9 kB ? eta -:--:--
   - -------------------------------------- 10.2/250.9 kB ? eta -:--:--
   ------------------- -------------------- 122.9/250.9 kB 1.8 MB/s eta 0:00:01
   ---------------------------------------- 250.9/250.9 kB 3.1 MB/s eta 0:00:00
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [24]:
import pandas as pd

data_frame = pd.read_csv("score.csv", encoding="cp949")

data_frame

   이름  점수
0  철수  90
1  영희  80

In [27]:

data_frame = pd.read_csv("score2.csv", encoding="cp949")
data_frame

   철수  90
0  영희  80

In [29]:
data_frame=pd.read_csv("score3.csv",encoding='cp949')
data_frame

  학생이름  시험점수
0   철수    90
1   영희    80

# excel파일로 저장하기

In [31]:
df.to_excel('list.xlsx')

# 인덱스 제외하고 저장

In [33]:
df.to_excel('list1.xlsx', index=False)

# 특정 시트 이름 지정

In [36]:
df.to_excel("list2.xlsx",sheet_name="시험결과",index=False)

In [37]:
pd.read_excel("list2.xlsx",sheet_name="시험결과")

   이름  점수
0  철수  90
1  영희  80

In [51]:
df1=pd.DataFrame({
    "이름":["철수","영희2"],
    "점수":[90,80]
})

df2=pd.DataFrame({
    "이름":["민수","지영"],
    "점수":[85,95]
})

In [52]:
with pd.ExcelWriter("result.xlsx",engine="openpyxl")as writer:
    df1.to_excel(writer, sheet_name='1반', index=False)
    df2.to_excel(writer, sheet_name='2반',index=False)

# 시트추가 저장(기존파일에 추가)

In [53]:
with pd.ExcelWriter("result.xlsx", engine="openpyxl",mode='a') as writer:
    df.to_excel(writer,sheet_name="3반",index=False)

여러 시트를 딕셔너리로 저장하는 방법

In [59]:
dfs={
    "1반": df1,
    "2반": df2
}

In [60]:

with pd.ExcelWriter('result.xlsx') as writer:
    for sheet, data in dfs.items():
        data.to_excel(writer, sheet_name=sheet, index=False)